[package]
name = "shared"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9"
photon_lib = { path = "../photon_lib" }
serde = { version = "1", features = ["derive"] }
